export enum ERROR_CODE {
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_API_KEY = "INVALID_API_KEY",

  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_ALREADY_REVIEWED = "TASK_ALREADY_REVIEWED",

  OPENAI_KEY_MISSING = "OPENAI_KEY_MISSING",
}
